### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tasinone** [CarlosDev314159/Web-Image-Downloader#1]
Got this error:

`Traceback (most recent call last):
  File "D:\python Scripts\Image Downloader\Web-Image-Downloader-main\app.py", line 33, in <module>
    download = wget.download(link)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by CarlosDev314159** [comment]
Hello, I'm sorry for this; I realized that the error you are facing is an HTTP 403 (Forbidden) error, indicating that the server is denying the request. I've updated the code, and I ask you to try again. If any further errors occur, please report them again."

**Comment by CarlosDev314159** [comment]
Hello, I'm sorry for this; I realized that the error you are facing is an HTTP 403 (Forbidden) error, indicating that the server is denying the request. I've updated the code, and I ask you to try again. If any further errors occur, please report them again.

**Comment by tasinone** [comment]
I got this error, is it because of the version mismatch?

![Screenshot_71](https://github.com/CarlosDev314159/Web-Image-Downloader/assets/33787196/85df4880-f73f-4153-a0fc-9486c2b4fc81)

**Comment by CarlosDev314159** [comment]
Hello, apologize for the confusion. I adjusted the compatibility with the idna library, and the error generated on line 66 was due to a non-existent variable. It will be a layout adjustment in the future. I hope everything is working correctly now. If any issues arise, I'll be here to resolve them.
